# Generated by Django 6.0.2 on 2026-02-25 06:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('color_code', models.CharField(choices=[('#FF3B6B', 'Noveon Pink'), ('#FF9F2D', 'Frillio Orange'), ('#22C55E', 'Success Green'), ('#D946EF', 'Splendid Purple'), ('#0EA5E9', 'Zofund Blue'), ('#06B6D4', 'Informatics Cyan'), ('#8B5CF6', 'Violet'), ('#EC4899', 'Deep Pink'), ('#64748B', 'Slate Grey'), ('#F59E0B', 'Amber'), ('#3366ff', 'Default Blue')], default='#3366ff', max_length=20)),
                ('status', models.CharField(default='Active', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('Employee', 'Employee'), ('Manager', 'Manager')], default='Employee', max_length=20)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='employee_portal.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailySubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('meeting_count', models.PositiveIntegerField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_submissions', to='employee_portal.employee')),
            ],
            options={
                'unique_together': {('employee', 'date')},
            },
        ),
        migrations.CreateModel(
            name='DailyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_blocker', models.BooleanField(default=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='employee_portal.dailysubmission')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_portal.employee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_portal.project')),
            ],
        ),
    ]
