# Generated by Django 6.0.2 on 2026-02-25 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_manager',
            field=models.BooleanField(default=False, help_text='Check this box if the employee is a manager.'),
        ),
    ]
