# Generated by Django 6.0.2 on 2026-03-08 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='temp_migration_fix',
            field=models.BooleanField(default=False),
        ),
    ]
