# Generated by Django 6.0.2 on 2026-03-10 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='acronym',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='client_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
