# Generated by Django 6.0.2 on 2026-02-07 19:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_portal', '0002_alter_dailytask_options_remove_employee_is_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytask',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
