# Generated by Django 6.0.2 on 2026-03-01 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_portal', '0002_employee_is_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysubmission',
            name='submitted_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
