# Generated by Django 6.0.2 on 2026-03-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_portal', '0003_employee_emergency_contact_employee_employee_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='color_code',
            field=models.CharField(default='#3366ff', max_length=20),
        ),
    ]
