# Generated by Django 6.0.2 on 2026-02-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_portal', '0004_employee_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='color_code',
            field=models.CharField(choices=[('#FF3B6B', 'Noveon Pink'), ('#FF9F2D', 'Frillio Orange'), ('#22C55E', 'Success Green'), ('#D946EF', 'Splendid Purple'), ('#0EA5E9', 'Zofund Blue'), ('#06B6D4', 'Informatics Cyan'), ('#8B5CF6', 'Violet'), ('#EC4899', 'Deep Pink'), ('#64748B', 'Slate Grey'), ('#F59E0B', 'Amber'), ('#3366ff', 'Default Blue')], default='#3366ff', max_length=20),
        ),
    ]
