# Generated by Django 6.0.2 on 2026-04-02 19:31

from django.db import migrations

# 1. PASTE THIS FUNCTION HERE
def migrate_designation_data(apps, schema_editor):
    Employee = apps.get_model('employee_portal', 'Employee')
    Designation = apps.get_model('employee_portal', 'Designation')

    for employee in Employee.objects.all():
        if employee.designation: 
            desig_obj, created = Designation.objects.get_or_create(name=employee.designation)
            employee.designation_new = desig_obj
            employee.save()
            
class Migration(migrations.Migration):

    dependencies = [
        ('employee_portal', '0005_designation_alter_employee_designation_and_more'),
    ]

    operations = [
    ]
