# Generated by Django 6.0.2 on 2026-04-02 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_portal', '0006_auto_20260403_0116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='designation',
        ),
        migrations.AlterField(
            model_name='employee',
            name='designation_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='employee_portal.designation'),
        ),
    ]
