# Generated by Django 6.0.2 on 2026-04-02 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_portal', '0007_remove_employee_designation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='designation_new',
            new_name='designation',
        ),
    ]
