# Generated by Django 6.0.2 on 2026-04-21 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_portal', '0008_rename_designation_new_employee_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='designation',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20),
        ),
    ]
