# Generated by Django 6.0.2 on 2026-04-22 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_portal', '0009_designation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='designation',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
