# Generated by Django 6.0.2 on 2026-04-22 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_portal', '0010_designation_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='designation',
            name='system_name',
            field=models.CharField(blank=True, help_text='Internal identifier, e.g. software_engineer', max_length=255, null=True, unique=True),
        ),
    ]
